name: Project Unit tests

on:
  push:
    branches: [ workflow, AddingDbToWf ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:7.0

    services:
      postgressrv:
        image: postgres
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Run tests
        run: dotnet test ./Instrument.Quote.Source.Srv.sln --configuration Release --verbosity m --no-restore
        env:
          TestENV_ConnectionStrings__DefaultConnection: "Host=postgressrv;Port=5433;Database=GitHubActions;Username=postgres;Password=postgres"

